name: wolfssl
version: 5.8.4
url: https://github.com/wolfSSL/wolfssl/archive/refs/tags/v5.8.4-stable.tar.gz
sha256: 2b702b7a66b0067bfd284408827b1e59288b357b0dd758d0089c062395f2a522
dependencies:
  required:
    - mspcrt
script: build.bat
