name: c-blosc2
version: 2.22.0
url: https://github.com/Blosc/c-blosc2/archive/refs/tags/v2.22.0.tar.gz
sha256: 6c6fe90babfa09bd3c544643d3fc3ea9516f9cbc74e8b3342f0d50416862b76f
dependencies:
  required:
    - lz4
    - mspcrt
    - zlib
script: build.bat
