name: CoinUtils
version: master
url: https://github.com/coin-or/CoinUtils.git
recursive: false
depth: 1
dependencies:
  required:
    - bzip2
    - mspcrt
    - Data-Sample
    - Data-Netlib
    - lapack
    - ThirdParty-ASL
    - ThirdParty-Glpk
    - zlib
    - readline
script: build.sh
