name: string-lite
version: 0.0.0
url: https://github.com/nonstd-lite/string-lite/archive/refs/tags/v0.0.0.tar.gz
sha256: 4bf4b13025fccd03cc75abce7c4bb63fde5a07878049f18bd3673e17eeec16b8
dependencies:
script: build.bat
