name: mesa
version: 25.3.3
url: https://archive.mesa3d.org/mesa-25.3.3.tar.xz
sha256: 05328b3891c000e6a110a3e7321d8bfbb21631d132bf86bd3d4a8f45c535ef6b
dependencies:
  required:
    - pkg-config
    - DirectX-Headers
    - freeglut
    - llvm-project
    - winflexbison
    - libva
script: build.bat
