name: hdf5
version: 2.0.0
url: https://github.com/HDFGroup/hdf5/archive/refs/tags/2.0.0.tar.gz
sha256: 3e6ae0430995c8ae724688c866f4dbb6feba9c6220583d72049fbb9b006c1cd5
dependencies:
  required:
    - libaec
    - perl
    - pkg-config
    - zlib
    - mspcrt
script: build.bat
