name: abseil-cpp
version: 20250814.1
url: https://github.com/abseil/abseil-cpp/archive/refs/tags/20250814.1.tar.gz
sha256: 1692f77d1739bacf3f94337188b78583cf09bab7e420d2dc6c5605a4f86785a1
dependencies:
  required:
    - mspcrt
script: build.bat
