name: Cgl
version: master
url: https://github.com/coin-or/Cgl.git
recursive: false
depth: 1
dependencies:
  required:
    - CoinUtils
    - mspcrt
    - Data-Sample
    - Osi
    - Clp
script: build.sh
