name: expected-lite
version: 0.10.0
url: https://github.com/nonstd-lite/expected-lite/archive/refs/tags/v0.10.0.tar.gz
sha256: cfe082e4ffedeeedac47763504102646a39c080599c7c1fe99299d6a1f99af92
dependencies:
script: build.bat
