name: fq
version: 0.15.1
url: https://github.com/wader/fq/archive/refs/tags/v0.15.1.tar.gz
sha256: 9f668394c33f3effd02b7d7a145f1087ce784e01d3d0c6e6ba41a899d5e349a7
dependencies:
script: build.bat
