name: any-lite
version: 0.4.0
url: https://github.com/nonstd-lite/any-lite/archive/refs/tags/v0.4.0.tar.gz
sha256: 889549098291a1313d2fc8cd12dcdab13214d05cdce7ed5fe2dc724cdd7b3125
dependencies:
script: build.bat
