name: level-zero
version: 1.26.0
url: https://github.com/oneapi-src/level-zero/archive/refs/tags/v1.26.0.tar.gz
sha256: 252dc01ffd2134ba25563d3851b755ff81cbda5982410296d09f3f54c118c16f
dependencies:
script: build.bat
