name: protobuf-c
version: 1.5.2
url: https://github.com/protobuf-c/protobuf-c/archive/refs/tags/v1.5.2.tar.gz
sha256: cea46eeaa19c52924938b582c5d128a6ed3b6fb5b3f4677476a1781cc06e03f3
dependencies:
  required:
    - mspcrt
    - zlib
script: build.bat
