name: span-lite
version: 0.11.0
url: https://github.com/nonstd-lite/span-lite/archive/refs/tags/v0.11.0.tar.gz
sha256: ef4e028e18ff21044da4b4641ca1bc8a2e2d656e2028322876c0e1b9b6904f9d
dependencies:
script: build.bat
