name: SuiteSparse
version: 7.12.1
url: https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/refs/tags/v7.12.1.tar.gz
sha256: 794ae22f7e38e2ac9f5cbb673be9dd80cdaff2cdf858f5104e082694f743b0ba
dependencies:
  required:
    - gmp
    - llvm-project
    - lz4
    - mpfr
    - mspcrt
    - OpenBLAS
    - zstd
script: build.bat
