name: OpenCV
version: 4.13.0
url: https://github.com/opencv/opencv/archive/refs/tags/4.13.0.tar.gz
sha256: 1d40ca017ea51c533cf9fd5cbde5b5fe7ae248291ddf2af99d4c17cf8e13017d
dependencies:
  required:
    - ffmpeg
    - libpng
    - libtiff
    - libwebp
    - nasm
    - oneTBB
    - OpenEXR
    - openblas
    - openjpeg
    - zlib
script: build.bat
