name: RandBLAS
version: 1.0.1
url: https://github.com/BallisticLA/RandBLAS/archive/refs/tags/1.0.1.tar.gz
sha256: e82e9b4de95d71cce9dad0c225e130f838f6d80b9be5ce5a77457f6b3a987d5a
dependencies:
  required:
    - blaspp
    - googletest
    - llvm-project
    - random123
script: build.bat
