name: jthread-lite
version: 0.1.0
url: https://github.com/nonstd-lite/jthread-lite/archive/refs/tags/v0.1.0.tar.gz
sha256: 05d8f591a83b5c3ea7361c178ddad6cb91ab7ab4c07a792c273667a004843ecd
dependencies:
script: build.bat
