name: oniguruma
version: 6.9.10
url: https://github.com/kkos/oniguruma/archive/refs/tags/v6.9.10.tar.gz
sha256: ad92309d0d13eebc27f6592e875f3efbfa3dda2bf6da5952e00f0a2120c921a8
script: build.bat
