name: libgit2
version: 1.9.1
url: https://github.com/libgit2/libgit2/archive/refs/tags/v1.9.1.tar.gz
sha256: 14cab3014b2b7ad75970ff4548e83615f74d719afe00aa479b4a889c1e13fc00
dependencies:
  required:
    - pkg-config
    - libssh2
    - openssl
    - pcre
    - zlib
script: build.bat
