name: libsamplerate
version: 0.2.2
url: https://github.com/libsndfile/libsamplerate/archive/refs/tags/0.2.2.tar.gz
sha256: 16e881487f184250deb4fcb60432d7556ab12cb58caea71ef23960aec6c0405a
dependencies:
  required:
    - libsndfile
    - fftw
script: build.bat
