name: ccache
version: 4.12.2
url: https://github.com/ccache/ccache/archive/refs/tags/v4.12.2.tar.gz
sha256: 89a9df3b291c4df9f8b9e1696c4f811e548568171954cb14c00f621c0db66127
dependencies:
  required:
    - BLAKE3
    - cpp-httplib
    - doctest
    - fmt
    - hiredis
    - minitrace
    - mspcrt
    - span-lite
    - tl-expected
    - xxHash
    - zstd
script: build.bat
