name: gstreamer
version: 1.27.2
url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.27.2.tar.xz
sha256: ce129c7ea92dce3063b029171d1324d203927132fc3e0cf92b784ddd055c241d
dependencies:
  required:
    - pkg-config
    - mspcrt
    - gettext
    - glib
    - gmp
    - gsl
    - gobject-introspection
script: build.bat
