name: icu4c
version: 78.1
url: https://github.com/unicode-org/icu/releases/download/release-78.1/icu4c-78.1-sources.tgz
sha256: 6217f58ca39b23127605cfc6c7e0d3475fe4b0d63157011383d716cb41617886
extras:
  - name: icu4c-data
    version: 78.1
    url: https://github.com/unicode-org/icu/releases/download/release-78.1/icu4c-78.1-data.zip
    sha256: e7b652244f27194e0ea46a0d21cfc714ee8a818e1fd82d51a93bc91516fdcf65
    target: source/data
    check: "if exist \"source\\data\\locales\" (exit 0) else (exit 1)"
dependencies:
  required:
    - mspcrt
script: build.sh
