name: type-lite
version: 0.2.0
url: https://github.com/nonstd-lite/type-lite/archive/refs/tags/v0.2.0.tar.gz
sha256: 47d6f78c3e8588f0a63e86c357d0d9e83543d754334df9dece7a4242047aea37
dependencies:
script: build.bat
