name: hiredis
version: 1.3.0
url: https://github.com/redis/hiredis/archive/refs/tags/v1.3.0.tar.gz
sha256: 25cee4500f359cf5cad3b51ed62059aadfc0939b05150c1f19c7e2829123631c
dependencies:
script: build.bat
