name: eigen
version: 5.0.0
url: https://gitlab.com/libeigen/eigen/-/archive/5.0.0/eigen-5.0.0.tar.bz2
sha256: bdca0ec740fb83be21fe038699923f4c589ead9ab904f4058a9c97752e60d50b
dependencies:
  required:
    - pkg-config
    - ADOL-C
    - boost
    - fftw
    - sparsehash
    - gmp
    - gsl
    - METIS
    - mpfr
    - mpreal
    - OpenBLAS
    - SuiteSparse
    - superlu
    - sparsehash
script: build.bat
