name: gst-plugins-good
version: 1.27.2
url: https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.27.2.tar.xz
sha256: 4f047416d71b102998db4cc513925cb317d87a3409d0ffae3ba218765b0f1ce5
dependencies:
  required:
    - pkg-config
    - mspcrt
    - gettext
    - glib
    - gobject-introspection
    - gstreamer
    - gst-plugins-base
script: build.bat
