name: libslirp
version: 4.9.1
url: https://gitlab.freedesktop.org/slirp/libslirp/-/archive/v4.9.1/libslirp-v4.9.1.tar.bz2
sha256: 3caff6e2de445f4995629d4929c55419f661b2b1d14f12481e155a71c1e8f811
dependencies:
  required:
    - glib
    - libiconv
script: build.bat
