name: openssl
version: 3.5.4
url: https://github.com/openssl/openssl/releases/download/openssl-3.5.4/openssl-3.5.4.tar.gz
sha256: 967311f84955316969bdb1d8d4b983718ef42338639c621ec4c34fddef355e99
dependencies:
  required:
    - brotli
    - nasm
    - perl
    - zlib
    - zstd
    - mspcrt
script: build.bat
