name: parallel
version: '20251122'
url: https://ftp.gnu.org/gnu/parallel/parallel-20251122.tar.bz2
sha256: 368d1982cfd9dbebb8cd0e444de6199559df94ac2dd1edf95f74350f0af1e84d
dependencies:
  required:
    - mspcrt
script: build.sh
