name: gst-plugins-base
version: 1.27.2
url: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.27.2.tar.xz
sha256: 6f530a0eac4fe3a8e5487c3eea7b1fac307e2a21f056d9b41747818a88be4bf6
dependencies:
  required:
    - pkg-config
    - mspcrt
    - gettext
    - glib
    - gobject-introspection
    - OpenCL-Headers
    - gstreamer
script: build.bat
