name: dlfcn-win32
version: 1.4.2
url: https://github.com/dlfcn-win32/dlfcn-win32/archive/refs/tags/v1.4.2.tar.gz
sha256: f61a874bc9163ab488accb364fd681d109870c86e8071f4710cbcdcbaf9f2565
dependencies:
script: build.bat
supports:
  - windows
