name: gettext
version: 0.25.1
url: https://ftp.gnu.org/pub/gnu/gettext/gettext-0.25.1.tar.xz
sha256: 2c8294be238f03fb3fa65b8051057e5b68167f3e21f08008070cf40a7051ba22
dependencies:
  required:
    - bzip2
    - libiconv
    - libxml2
    - libunistring
    - mspcrt
    - xz
script: build.sh
