name: oneTBB
version: 2022.3.0
url: https://github.com/uxlfoundation/oneTBB/archive/refs/tags/v2022.3.0.tar.gz
sha256: 01598a46c1162c27253a0de0236f520fd8ee8166e9ebb84a4243574f88e6e50a
dependencies:
  required:
    - hwloc
    - mspcrt
script: build.bat
