name: json-c
version: '0.18'
url: https://github.com/json-c/json-c/archive/refs/tags/json-c-0.18-20240915.tar.gz
sha256: 3112c1f25d39eca661fe3fc663431e130cc6e2f900c081738317fba49d29e298
dependencies:
  required:
    - mspcrt
script: build.bat
