name: mspcrt
version: 1.2.0
url: https://github.com/jiangjianshan/mspcrt/archive/refs/tags/v1.2.0.tar.gz
sha256: 1bcce7a00a4c33b8160d0589e7ea9176705c5bc5da5ee59c2327d711edc8d2c1
script: build.bat
supports:
  - windows
