name: mspcrt
version: 1.0.0
url: https://github.com/jiangjianshan/mspcrt/archive/refs/tags/v1.0.0.tar.gz
sha256:
dependencies:
  required:
    - dirent
    - dlfcn-win32
    - winpthreads
script: build.bat
supports:
  - windows
