name: googletest
version: 1.17.0
url: https://github.com/google/googletest/archive/refs/tags/v1.17.0.tar.gz
sha256: 65fab701d9829d38cb77c14acdc431d2108bfdbf8979e40eb8ae567edf10b27c
dependencies:
  required:
    - abseil-cpp
    - re2
script: build.bat
