name: DirectX-Headers
version: 1.618.2
url: https://github.com/microsoft/DirectX-Headers/archive/refs/tags/v1.618.2.tar.gz
sha256: 62004f45e2ab00cbb5c7f03c47262632c22fbce0a237383fc458d9324c44cf36
dependencies:
  required:
    - pkg-config
script: build.bat
