name: string-view-lite
version: 1.8.0
url: https://github.com/nonstd-lite/string-view-lite/archive/refs/tags/v1.8.0.tar.gz
sha256: 9b38c32621eb1a81a7fa59427144309225c414a7bae522ab3a2d9ae239dd35be
dependencies:
script: build.bat
