name: szip
version: 2.1.1
url: https://docs.hdfgroup.org/archive/support/ftp/lib-external/szip/2.1.1/src/szip-2.1.1.tar.gz
sha256: 21ee958b4f2d4be2c9cabfa5e1a94877043609ce86fde5f286f105f7ff84d412
dependencies:
  required:
    - mspcrt
script: build.bat
