name: status-value-lite
version: 1.1.0
url: https://github.com/nonstd-lite/status-value-lite/archive/refs/tags/v1.1.0.tar.gz
sha256: adcc9f3938b7805c1c465b5cde4e96143e126e7ddbccc00a53b452a8cc4d8ba8
dependencies:
script: build.bat
