name: winpthreads
version: 13.0.0
url: https://github.com/mingw-w64/mingw-w64/archive/refs/tags/v13.0.0.tar.gz
sha256: 1a910473313a329316025fa4563160deae378884e4b8ee573d1d03ac006b2e61
extract: mingw-w64-13.0.0/mingw-w64-libraries/winpthreads
dependencies:
  required:
    - dlfcn-win32
script: build.sh
supports:
  - windows
