name: libpano13
version: 2.9.23
url: https://sourceforge.net/projects/panotools/files/libpano13/libpano13-2.9.23/libpano13-2.9.23.tar.gz
sha256: e7c076d37a14c39434962115e47ddbe18452ca3de5ce40e2aaefa7cf5815ea28
dependencies:
  required:
    - libjpeg-turbo
    - libtiff
    - libpng
    - perl
    - zlib
script: build.bat
