name: swig
version: 4.4.1
url: http://prdownloads.sourceforge.net/swig/swig-4.4.1.tar.gz
sha256: 40162a706c56f7592d08fd52ef5511cb7ac191f3593cf07306a0a554c6281fcf
dependencies:
  required:
    - mspcrt
    - pcre2
script: build.bat
