name: units
version: '2.24'
url: https://ftp.gnu.org/gnu/units/units-2.24.tar.gz
sha256: 1e502c4edfacf20b29284716c72e5ddb51a495a2365d7b03e7960494c4a0c902
dependencies:
  required:
    - mspcrt
script: build.sh
