name: zfp
version: 1.0.1
url: https://github.com/LLNL/zfp/archive/refs/tags/1.0.1.tar.gz
sha256: 4984db6a55bc919831966dd17ba5e47ca7ac58668f4fd278ebd98cd2200da66f
dependencies:
script: build.bat
