name: lunasvg
version: 3.5.0
url: https://github.com/sammycage/lunasvg/archive/refs/tags/v3.5.0.tar.gz
sha256: 1abf1472ee6c4d19797916e8cc3c2e4b628e0d81178ffac60bdb0d457e32c690
dependencies:
  required:
    - mspcrt
script: build.bat
