name: gnun
version: '1.5'
url: https://ftp.gnu.org/gnu/gnun/gnun-1.5.tar.gz
sha256: c618234f75c3d63e6a2db4d61039bbb95bed78f32889e6d1070c1bd6b62519a3
dependencies:
  required:
    - mspcrt
script: build.sh
