name: libsndfile
version: 1.2.2
url: https://github.com/libsndfile/libsndfile/archive/refs/tags/1.2.2.tar.gz
sha256: ffe12ef8add3eaca876f04087734e6e8e029350082f3251f565fa9da55b52121
dependencies:
  required:
    - flac
    - libogg
    - libvorbis
    - opus
    - speex
    - sqlite
script: build.bat
