name: tl-expected
version: 1.3.1
url: https://github.com/TartanLlama/expected/archive/refs/tags/v1.3.1.tar.gz
sha256: 9a04f4f472fbb5c30bf60402f1ca626c4a76987f867978d0b8a35d7ab3fb8fe7
dependencies:
  required:
    - Catch2
script: build.bat
