name: fluidsynth
version: 2.5.1
url: https://github.com/FluidSynth/fluidsynth/archive/refs/tags/v2.5.1.tar.gz
sha256: 10b2e32ba78c72ac1384965c66df06443a4bd0ab968dcafaf8fa17086001bf03
dependencies:
  required:
    - doxygen
    - gcem
    - glib
    - libxslt
    - libsndfile
    - llvm-project
    - mspcrt
    - readline
    - SDL3
script: build.bat
