name: raylib
version: '5.5'
url: https://github.com/raysan5/raylib/archive/refs/tags/5.5.tar.gz
sha256: aea98ecf5bc5c5e0b789a76de0083a21a70457050ea4cc2aec7566935f5e258e
dependencies:
script: build.bat
