name: mpg123
version: 1.33.3
url: https://sourceforge.net/projects/mpg123/files/mpg123/1.33.3/mpg123-1.33.3.tar.bz2
sha256: 6a0c6472dd156e213c2068f40115ebbb73978c2d873e66bae2a250e2d2198d26
dependencies:
  required:
    - mspcrt
    - openal-soft
    - SDL2
script: build.bat
