name: scope-lite
version: 0.3.0
url: https://github.com/nonstd-lite/scope-lite/archive/refs/tags/v0.3.0.tar.gz
sha256: c66b54c29c2982341945c7258b7e2c0b49558848f50ac42698cb34aa52f78446
dependencies:
script: build.bat
