name: vim
version: master
url: https://github.com/vim/vim.git
recursive: false
depth: 1
dependencies:
  required:
    - lua
    - libsodium
    - gettext
    - gettext:x86
    - perl
    - ruby
    - tcl
script: build.bat
