name: byte-lite
version: 0.3.0
url: https://github.com/nonstd-lite/byte-lite/archive/refs/tags/v0.3.0.tar.gz
sha256: 1a19e237b12bb098297232b0a74ec08c18ac07ac5ac6e659c1d5d8a4ed0e4813
dependencies:
script: build.bat
